### ISSUE TITLE
ETIMEDOUT error with CircuitPython 7.x

### ISSUE THREAD

**Issue by mousethief** [adafruit/Adafruit_CircuitPython_LTR390#12]
(Referencing Adafruit forum topic https://forums.adafruit.com/viewtopic.php?f=60&t=185282)
- Arduino board:  Feather RP2040 (Adafruit product #4884), QTPy RP2040 (Adafruit product #4900), possibly others.

- CircuitPython 6.3.0, 7.0.0, 7.1.0-beta1

- List the steps to reproduce the problem below 

Run on CircuitPython 7.x on an RP2040-based board:
```
# Bug Report Test Code, LTR390 issue with CPy 7.x on RP2040

import board
import time

import adafruit_ltr390

i2c_bus = board.I2C()
sens_light = adafruit_ltr390.LTR390(i2c_bus)

while True:
	data_light_uv = sens_light.uvs
	data_light_light = sens_light.light

	print("UV:  ", data_light_uv, "Ambient Light: ", data_light_light)

	time.sleep(5)
```

> code.py output:
> Traceback (most recent call last):
>   File "code.py", line 10, in <module>
>   File "adafruit_ltr390.py", line 286, in __init__
>   File "adafruit_ltr390.py", line 292, in initialize
>   File "adafruit_ltr390.py", line 315, in _reset
>   File "adafruit_register/i2c_bit.py", line 43, in __get__
> OSError: [Errno 116] ETIMEDOUT

CircuitPython 6.3.0 on the RP2040-based board works as expected:
> code.py output:
> UV:   1 Ambient Light: 157
> ...

CircuitPython 7.0.0 on a different board (Feather nRF52840 Express) also works as expected.

**Comment by mousethief** [comment]
Some messing around (physically handling the hardware), I've gotten a 'OSError: [Errno 19] Unsupported operation' (unreliably so far) in place of the ETIMEDOUT. I don't know if that is useful, but it is interesting.

**Comment by caternuson** [comment]
Is this a dupe of #11 ?

**Comment by mousethief** [comment]
Lib version 1.1.3 works (when tested) on Feather RP2040 and Macropad.
